import type { Agent } from "./agents";
import type { BusinessPlanData, AgentOutput } from "@/context/project-context";

export async function exportToPdf(element: HTMLElement, filename: string): Promise<void> {
  const html2pdf = (await import("html2pdf.js")).default;
  await html2pdf()
    .set({
      margin: [10, 10, 10, 10],
      filename: `${filename}.pdf`,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, logging: false, backgroundColor: "#080F14" },
      jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
      pagebreak: { mode: ["avoid-all", "css", "legacy"] },
    })
    .from(element)
    .save();
}

function createPrintContainer(): HTMLDivElement {
  const div = document.createElement("div");
  div.style.cssText =
    "position:fixed;left:-9999px;top:0;width:794px;background-color:#080F14;color:#BDB7C3;padding:40px;font-family:Arial,sans-serif;font-size:13px;line-height:1.7;";
  document.body.appendChild(div);
  return div;
}

function header(title: string, subtitle: string): string {
  return `
    <div style="margin-bottom:28px;border-bottom:2px solid #00D1FF;padding-bottom:16px;">
      <div style="color:#00D1FF;font-size:22px;font-weight:bold;letter-spacing:3px;text-transform:uppercase;">${title}</div>
      <div style="color:#5A6470;font-size:12px;margin-top:6px;letter-spacing:1px;">${subtitle}</div>
    </div>`;
}

function sectionBlock(label: string, accentColor: string, content: string): string {
  return `
    <div style="margin-bottom:32px;page-break-inside:avoid;">
      <div style="color:${accentColor};font-size:13px;font-weight:bold;letter-spacing:2px;text-transform:uppercase;border-bottom:1px solid #1E2730;padding-bottom:8px;margin-bottom:14px;">
        ${label}
      </div>
      <div style="color:#D0CBD8;font-size:12px;line-height:1.8;white-space:pre-wrap;">${content}</div>
    </div>`;
}

export async function exportAgentPdf(agent: Agent, output: AgentOutput, projectName: string): Promise<void> {
  const div = createPrintContainer();
  const accentColors: Record<string, string> = {
    emerald: "#10b981", amber: "#f59e0b", rose: "#f43f5e", cyan: "#00D1FF",
    violet: "#8b5cf6", orange: "#f97316", blue: "#3b82f6", indigo: "#6366f1",
    pink: "#ec4899", gold: "#eab308", red: "#ef4444", purple: "#a855f7",
  };
  const accent = accentColors[agent.color] || "#00D1FF";

  div.innerHTML = `
    ${header(`${agent.name} — Agent Report`, `${agent.role} · Project: ${projectName} · ${new Date().toLocaleDateString()}`)}
    <div style="display:flex;gap:24px;margin-bottom:28px;">
      <div style="background:#0A121A;border:1px solid ${accent}33;border-radius:6px;padding:14px 20px;flex:1;">
        <div style="color:#5A6470;font-size:10px;letter-spacing:1px;text-transform:uppercase;margin-bottom:4px;">Role</div>
        <div style="color:${accent};font-size:14px;font-weight:bold;">${agent.role}</div>
      </div>
      <div style="background:#0A121A;border:1px solid ${accent}33;border-radius:6px;padding:14px 20px;flex:2;">
        <div style="color:#5A6470;font-size:10px;letter-spacing:1px;text-transform:uppercase;margin-bottom:4px;">Specialization</div>
        <div style="color:#BDB7C3;font-size:13px;">${agent.description}</div>
      </div>
    </div>
    ${sectionBlock("Analysis & Deliverables", accent, output.content || "No output generated.")}
    <div style="margin-top:40px;border-top:1px solid #1E2730;padding-top:12px;color:#3A3F45;font-size:10px;letter-spacing:1px;">
      Generated by A2G STACK3 · ${new Date().toLocaleString()} · Powered by Gemini AI
    </div>`;

  try {
    await exportToPdf(div, `A2G_${agent.name.replace(/\s+/g, "_")}_${projectName.replace(/\s+/g, "_")}`);
  } finally {
    document.body.removeChild(div);
  }
}

export async function exportExecutiveReport(
  plan: BusinessPlanData,
  agentOutputs: Record<string, AgentOutput>,
  agents: Agent[]
): Promise<void> {
  const div = createPrintContainer();
  const keyAgentIds = ["1", "2", "3", "4", "5", "6", "7", "9", "10", "13", "14", "21"];
  const accentColors: Record<string, string> = {
    emerald: "#10b981", amber: "#f59e0b", rose: "#f43f5e", cyan: "#00D1FF",
    violet: "#8b5cf6", orange: "#f97316", blue: "#3b82f6", indigo: "#6366f1",
    pink: "#ec4899", gold: "#eab308", red: "#ef4444", purple: "#a855f7",
  };

  const agentSections = keyAgentIds
    .map(id => {
      const agent = agents.find(a => a.id === id);
      const output = agentOutputs[id];
      if (!agent || !output?.content) return "";
      const accent = accentColors[agent.color] || "#00D1FF";
      return sectionBlock(`${agent.name} (${agent.role})`, accent, output.content);
    })
    .join("");

  const tocItems = keyAgentIds
    .map(id => {
      const agent = agents.find(a => a.id === id);
      if (!agent) return "";
      return `<div style="color:#BDB7C3;font-size:12px;padding:4px 0;border-bottom:1px dotted #1E2730;">${agent.name} <span style="color:#5A6470;font-size:11px;">— ${agent.role}</span></div>`;
    })
    .join("");

  div.innerHTML = `
    ${header(`A2G STACK3 — Executive Report`, `Project: ${plan.projectName} · Generated ${new Date().toLocaleDateString()} · Powered by Gemini AI`)}

    <div style="background:#0A121A;border:1px solid #1E2730;border-radius:6px;padding:16px 20px;margin-bottom:32px;">
      <div style="color:#00D1FF;font-size:11px;letter-spacing:2px;text-transform:uppercase;margin-bottom:8px;">Core Thesis</div>
      <div style="color:#BDB7C3;font-size:12px;line-height:1.7;">${plan.description}</div>
    </div>

    <div style="margin-bottom:32px;">
      <div style="color:#5A6470;font-size:11px;letter-spacing:2px;text-transform:uppercase;margin-bottom:12px;">Table of Contents</div>
      ${tocItems}
    </div>

    <div style="border-top:2px solid #1E2730;padding-top:28px;margin-top:8px;">
      ${agentSections}
    </div>

    <div style="margin-top:40px;border-top:1px solid #1E2730;padding-top:12px;color:#3A3F45;font-size:10px;letter-spacing:1px;">
      Confidential — A2G STACK3 Multi-Agent Executive Report · ${new Date().toLocaleString()}
    </div>`;

  try {
    await exportToPdf(div, `A2G_Executive_Report_${plan.projectName.replace(/\s+/g, "_")}`);
  } finally {
    document.body.removeChild(div);
  }
}
