import { Router, type IRouter } from "express";
import { eq, count, and } from "drizzle-orm";
import { db, projectsTable, agentsTable, tasksTable, insightsTable } from "@workspace/db";

const router: IRouter = Router();

router.get("/dashboard/summary", async (_req, res): Promise<void> => {
  const [[totalProjectsRow], [totalAgentsRow], [activeAgentsRow], [totalTasksRow],
    [completedTasksRow], [pendingTasksRow], [inProgressTasksRow], [totalInsightsRow], [highImpactRow]] =
    await Promise.all([
      db.select({ count: count() }).from(projectsTable),
      db.select({ count: count() }).from(agentsTable),
      db.select({ count: count() }).from(agentsTable).where(eq(agentsTable.status, "active")),
      db.select({ count: count() }).from(tasksTable),
      db.select({ count: count() }).from(tasksTable).where(eq(tasksTable.status, "completed")),
      db.select({ count: count() }).from(tasksTable).where(eq(tasksTable.status, "pending")),
      db.select({ count: count() }).from(tasksTable).where(eq(tasksTable.status, "in_progress")),
      db.select({ count: count() }).from(insightsTable),
      db.select({ count: count() }).from(insightsTable).where(eq(insightsTable.impact, "high")),
    ]);

  res.json({
    totalProjects: Number(totalProjectsRow?.count ?? 0),
    totalAgents: Number(totalAgentsRow?.count ?? 0),
    activeAgents: Number(activeAgentsRow?.count ?? 0),
    totalTasks: Number(totalTasksRow?.count ?? 0),
    completedTasks: Number(completedTasksRow?.count ?? 0),
    pendingTasks: Number(pendingTasksRow?.count ?? 0),
    inProgressTasks: Number(inProgressTasksRow?.count ?? 0),
    totalInsights: Number(totalInsightsRow?.count ?? 0),
    highImpactInsights: Number(highImpactRow?.count ?? 0),
  });
});

router.get("/dashboard/activity", async (_req, res): Promise<void> => {
  const [recentTasks, recentInsights] = await Promise.all([
    db
      .select({
        id: tasksTable.id,
        title: tasksTable.title,
        status: tasksTable.status,
        createdAt: tasksTable.createdAt,
        completedAt: tasksTable.completedAt,
        agentName: agentsTable.name,
        projectName: projectsTable.name,
      })
      .from(tasksTable)
      .leftJoin(agentsTable, eq(tasksTable.agentId, agentsTable.id))
      .leftJoin(projectsTable, eq(tasksTable.projectId, projectsTable.id))
      .orderBy(tasksTable.updatedAt)
      .limit(10),
    db
      .select({
        id: insightsTable.id,
        title: insightsTable.title,
        createdAt: insightsTable.createdAt,
        agentName: agentsTable.name,
        projectName: projectsTable.name,
      })
      .from(insightsTable)
      .leftJoin(agentsTable, eq(insightsTable.agentId, agentsTable.id))
      .leftJoin(projectsTable, eq(insightsTable.projectId, projectsTable.id))
      .orderBy(insightsTable.createdAt)
      .limit(10),
  ]);

  const activity = [
    ...recentTasks.map((t) => ({
      id: `task-${t.id}`,
      type: t.completedAt ? "task_completed" : "task_created",
      title: t.completedAt ? `Task completed: ${t.title}` : `Task created: ${t.title}`,
      description: `Status: ${t.status}`,
      agentName: t.agentName ?? undefined,
      projectName: t.projectName ?? undefined,
      createdAt: t.completedAt ?? t.createdAt,
    })),
    ...recentInsights.map((i) => ({
      id: `insight-${i.id}`,
      type: "insight_generated",
      title: `Insight: ${i.title}`,
      description: `Generated by ${i.agentName ?? "agent"}`,
      agentName: i.agentName ?? undefined,
      projectName: i.projectName ?? undefined,
      createdAt: i.createdAt,
    })),
  ].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()).slice(0, 15);

  res.json(activity);
});

router.get("/dashboard/agent-performance", async (_req, res): Promise<void> => {
  const agents = await db
    .select({
      agentId: agentsTable.id,
      agentName: agentsTable.name,
      agentType: agentsTable.type,
      status: agentsTable.status,
      tasksCompleted: agentsTable.tasksCompleted,
      insightsGenerated: agentsTable.insightsGenerated,
    })
    .from(agentsTable)
    .orderBy(agentsTable.tasksCompleted);

  const tasksPending = await db
    .select({ agentId: tasksTable.agentId, count: count() })
    .from(tasksTable)
    .where(eq(tasksTable.status, "pending"))
    .groupBy(tasksTable.agentId);

  const pendingMap = new Map(tasksPending.map((t) => [t.agentId, Number(t.count)]));

  res.json(
    agents.map((a) => ({
      agentId: a.agentId,
      agentName: a.agentName,
      agentType: a.agentType,
      status: a.status,
      tasksCompleted: a.tasksCompleted,
      tasksPending: pendingMap.get(a.agentId) ?? 0,
      insightsGenerated: a.insightsGenerated,
    }))
  );
});

export default router;
